export const FETCH_RATES_PENDING = 'FETCH_RATES_PENDING';
export const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS';
export const FETCH_RATES_ERROR = 'FETCH_RATES_ERROR';

export const FAVORITE_RATES_ADD = 'FAVORITE_RATES_ADD';
export const FAVORITE_RATES_REMOVE = 'FAVORITE_RATES_REMOVE';
export const FAVORITE_RATES_REMOVE_ALL = 'FAVORITE_RATES_REMOVE_ALL';
