export const FETCH_RATES_PENDING = 'FETCH_RATES_PENDING';
export const FETCH_RATES_SUCCESS = 'FETCH_RATES_SUCCESS';
export const FETCH_RATES_ERROR = 'FETCH_RATES_ERROR';

export const FOLLOWED_RATES_ADD = 'FOLLOWED_RATES_ADD';
export const FOLLOWED_RATES_REMOVE = 'FOLLOWED_RATES_REMOVE';
export const FOLLOWED_RATES_REMOVE_ALL = 'FOLLOWED_RATES_REMOVE_ALL';
